version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:7860"
    volumes:
      - ./server/data:/app/server/data
    environment:
      - APP_ENV=${APP_ENV:-development}
      - SECRET_KEY=${SECRET_KEY}
      - DEFAULT_ADMIN_PWD=${DEFAULT_ADMIN_PWD}
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/server/data/nongsan_v2.sqlite3}
      - HF_HOME=/app/server/data/hf_cache
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
    restart: always
